# Generated by Django 4.2.5 on 2023-09-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'Article'), ('NW', 'News')], max_length=2),
        ),
    ]
