# Generated by Django 4.2.5 on 2023-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(choices=[('PL', 'Politics'), ('SP', 'Sport'), ('ED', 'Education'), ('SC', 'Science'), ('GN', 'General')], default='GN', max_length=2),
        ),
    ]
